# Generated by Django 3.2.5 on 2021-09-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=50)),
                ('category_name', models.CharField(max_length=90)),
                ('discription', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
            ],
        ),
    ]
