# Generated by Django 3.2.5 on 2021-09-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblfeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.CharField(max_length=50)),
                ('category_id', models.CharField(max_length=50)),
                ('feed', models.CharField(max_length=90)),
                ('discription', models.CharField(max_length=100)),
            ],
        ),
    ]
