# Generated by Django 3.2.5 on 2021-09-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0002_tblfeed'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblvaccin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_id', models.CharField(max_length=30)),
                ('category_id', models.CharField(max_length=30)),
                ('vaccination', models.CharField(max_length=90)),
                ('details', models.CharField(max_length=90)),
            ],
        ),
    ]
