# Generated by Django 3.2.5 on 2021-09-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0003_tblvaccin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbldoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=90)),
                ('qualification', models.CharField(max_length=90)),
                ('speciality', models.CharField(max_length=90)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
            ],
        ),
    ]
