# Generated by Django 3.2.5 on 2021-09-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0005_tblnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblpets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_id', models.CharField(max_length=70)),
                ('pet_name', models.CharField(max_length=90)),
                ('user_id', models.CharField(max_length=90)),
                ('category_id', models.CharField(max_length=90)),
                ('photo', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(max_length=80)),
            ],
        ),
    ]
