# Generated by Django 3.2.5 on 2021-09-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0006_tblpets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblpets',
            name='price',
            field=models.CharField(max_length=90),
        ),
    ]
