# Generated by Django 3.2.5 on 2021-09-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0007_alter_tblpets_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblquery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(max_length=60)),
                ('user_id', models.CharField(max_length=60)),
                ('query', models.CharField(max_length=100)),
                ('replay', models.CharField(max_length=100)),
            ],
        ),
    ]
