# Generated by Django 3.2.5 on 2021-09-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0008_tblquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=80)),
                ('pet_id', models.CharField(max_length=80)),
                ('user_id', models.CharField(max_length=80)),
                ('review', models.CharField(max_length=100)),
                ('review_date', models.DateField()),
            ],
        ),
    ]
