# Generated by Django 3.2.5 on 2021-09-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0009_tblreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblcomplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(max_length=80)),
                ('pet_id', models.CharField(max_length=80)),
                ('user_id', models.CharField(max_length=80)),
                ('complaint', models.CharField(max_length=100)),
                ('complaint_date', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='tblreview',
            name='review_date',
            field=models.CharField(max_length=80),
        ),
    ]
