# Generated by Django 3.2.5 on 2021-09-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0010_auto_20210914_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=80)),
                ('category', models.CharField(max_length=90)),
                ('name', models.CharField(max_length=90)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
