# Generated by Django 3.2.5 on 2021-09-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0011_tblregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbllogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=90)),
                ('category', models.CharField(max_length=90)),
            ],
        ),
    ]
