# Generated by Django 3.2.5 on 2021-09-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0012_tbllogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=80)),
                ('pet_id', models.CharField(max_length=80)),
                ('user_id', models.CharField(max_length=80)),
                ('order_date', models.CharField(max_length=80)),
                ('remark', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=80)),
            ],
        ),
    ]
