# Generated by Django 3.2.5 on 2021-09-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0013_tblorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblquery',
            name='status',
            field=models.CharField(default='pending', max_length=80),
            preserve_default=False,
        ),
    ]
